apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: ${{ values.component_id }}
  description: ${{ values.description }}
  annotations:
    github.com/project-slug: ${{ values.repo_owner }}/${{ values.repo_name }}
    backstage.io/techdocs-ref: dir:.
  tags:
    - nodejs
    - express
    - backend
    - ${{ values.environment }}
spec:
  type: service
  lifecycle: ${{ values.lifecycle }}
  owner: ${{ values.owner }}
  system: ${{ values.system | default("default") }}